### ISSUE TITLE
Integrating jshint-gem to display JS error??

### ISSUE THREAD

**Issue by sourabh-clarion** [arvind-clarion/qmeter#8]
Qmeter show for JS files ?

**Comment by sourabh-clarion** [comment]
https://github.com/rquinlivan/jshint-gem 

https://rubygems.org/gems/jshint_on_rails

**Comment by parth-clarion** [comment]
For JavaScript related errors need to use 'jshint' gem and for CoffeeScript 'coffeelint' should be used

**Comment by parth-clarion** [comment]
Added feature
